# Generated by Django 2.2 on 2021-06-04 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='login_and_profile.House')),
            ],
        ),
    ]
