# Generated by Django 2.2 on 2021-06-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_profile', '0003_housenotifications_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housenotifications',
            name='sender',
        ),
    ]
