# Generated by Django 2.2 on 2021-06-04 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_profile', '0005_housenotifications_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housenotifications',
            name='message',
        ),
        migrations.AddField(
            model_name='housenotifications',
            name='action',
            field=models.CharField(choices=[('PURCHASED', 'purchased'), ('INVITED', 'invited'), ('CREATED', 'created'), ('HELPED', 'helped purchase')], default='CREATED', max_length=32),
        ),
        migrations.AddField(
            model_name='housenotifications',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_notification', to='login_and_profile.User'),
        ),
        migrations.AlterField(
            model_name='housenotifications',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_notification', to='login_and_profile.User'),
        ),
    ]
