# Generated by Django 2.2 on 2021-06-04 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_profile', '0006_auto_20210604_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='housenotifications',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_notification', to='login_and_profile.Item'),
        ),
    ]
